# Generated by Django 6.0 on 2025-12-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.CharField(default='Satisfactory', max_length=100),
        ),
    ]
