# Generated by Django 5.2.7 on 2025-12-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
    ]
