# Generated by Django 6.0 on 2025-12-06 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='ups',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ups_units', to='api.branch'),
        ),
    ]
